import streamlit as st

from components import hero_section, feature_card, snapshot_card, section_intro


def render_overview(data):
    daily = data["daily"]
    events = data["events"]
    metrics = data["metrics"]
    annual_mhw = data["annual_mhw"]
    enso = data["enso"]

    total_days = len(daily)
    event_count = len(events)
    best_model = metrics.sort_values("rmse").iloc[0]
    max_intensity = events["max_intensity"].max()
    corr = enso[["oni", "sst_anomaly"]].corr().loc["oni", "sst_anomaly"]
    most_active_year = int(
        annual_mhw.sort_values("total_mhw_days", ascending=False).iloc[0]["year"]
    )

    hero_section()

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        feature_card(
            "🌡",
            "SST Trends",
            "Explore long-term and seasonal ocean temperature patterns.",
            "#60A5FA",
        )

    with col2:
        feature_card(
            "🔥",
            "Marine Heatwaves",
            "Detect extreme warm-water events using climatological thresholds.",
            "#FB923C",
        )

    with col3:
        feature_card(
            "🌎",
            "ENSO Analysis",
            "Analyze El Niño and La Niña impacts on California SST anomalies.",
            "#4ADE80",
        )

    with col4:
        feature_card(
            "🤖",
            "Forecasting",
            "Compare machine learning models for short-term SST prediction.",
            "#C084FC",
        )

    st.divider()

    section_intro(
        "Executive Snapshot", "Key project statistics and results at a glance."
    )

    col1, col2, col3, col4, col5, col6 = st.columns(6)

    with col1:
        snapshot_card("Study Period", "1982–2024", "43 years")

    with col2:
        snapshot_card("Daily NOAA Records", f"{total_days:,}", "Total days")

    with col3:
        snapshot_card("Detected MHW Events", f"{event_count}", "Total events")

    with col4:
        snapshot_card(
            "Max MHW Intensity", f"{max_intensity:.2f} °C", "Above climatology"
        )

    with col5:
        snapshot_card("ENSO–SST Corr.", f"{corr:.3f}", "Positive relationship")

    with col6:
        snapshot_card(
            "Best Model", best_model["model"], f"RMSE {best_model['rmse']:.3f} °C"
        )

    st.divider()

    section_intro("Key Findings", "Main insights generated by the analytics workflow.")

    st.markdown(
        """
- California coast SST shows strong seasonal variability and meaningful long-term warming signals.
- Marine heatwave activity is especially prominent during major warm periods, including 2014–2016.
- El Niño months are associated with warmer California SST anomalies and more marine heatwave days.
- ONI shows a positive lag relationship with California SST anomalies, peaking around a two-month lead.
- Short-term SST forecasting performs well using lagged SST, rolling statistics, seasonality, and climate indicators.
"""
    )

    st.divider()

    section_intro(
        "Explore the Platform",
        "Navigate through the analytical modules to explore different aspects of California ocean climate variability.",
    )

    col1, col2 = st.columns(2)

    with col1:
        st.markdown(
            """
### 🌡 SST Trends
Long-term SST trend, daily variability, and seasonal cycle.

### 🔥 Marine Heatwaves
Marine heatwave detection, yearly event counts, MHW days, and strongest events.
"""
        )

    with col2:
        st.markdown(
            """
### 🌎 ENSO Analysis
ONI relationships, ENSO phase comparison, lag analysis, and SST anomalies.

### 🤖 Forecasting
Model comparison, prediction results, and short-term SST forecasting.
"""
        )

    st.success(
        "This dashboard is designed as a portfolio-ready decision-support demo for Blue Economy, ocean analytics, and climate-tech opportunities."
    )
